# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200619_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
