# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-21 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permission_url_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('title', 'weight')]),
        ),
    ]
