# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20200627_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=36),
        ),
    ]
